import React, { useState } from 'react';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Download, Loader2 } from 'lucide-react';
import { base44 } from '@/api/base44Client';

export default function DailyReportViewer({ report, isOpen, onClose, serviceUser }) {
  const [isDownloading, setIsDownloading] = useState(false);

  if (!report) return null;

  const handleDownload = async () => {
    setIsDownloading(true);
    try {
      const response = await base44.functions.invoke('downloadDailyReport', {
        report_id: report.id,
        service_user_name: serviceUser?.full_name || 'Report'
      });

      if (response.data) {
        let pdfData = response.data;
        
        // Handle different response formats
        if (typeof pdfData === 'string') {
          pdfData = new TextEncoder().encode(pdfData);
        } else if (!(pdfData instanceof ArrayBuffer) && !(pdfData instanceof Uint8Array)) {
          pdfData = new Uint8Array(Object.values(pdfData));
        }
        
        const blob = new Blob([pdfData], { type: 'application/pdf' });
        const url = window.URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `Daily_Report_${serviceUser?.full_name || 'Report'}_${report.report_date}.pdf`;
        document.body.appendChild(a);
        a.click();
        
        setTimeout(() => {
          window.URL.revokeObjectURL(url);
          a.remove();
        }, 100);
      }
    } catch (error) {
      console.error('Error downloading report:', error);
    } finally {
      setIsDownloading(false);
    }
  };

  const reportDate = new Date(report.report_date).toLocaleDateString('en-GB', { 
    weekday: 'long', 
    year: 'numeric', 
    month: 'long', 
    day: 'numeric' 
  });

  const generatedDate = new Date(report.created_date).toLocaleString('en-GB');

  return (
    <Dialog open={isOpen} onOpenChange={(open) => !open && onClose()}>
      <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle>Daily Sitting Log Report</DialogTitle>
        </DialogHeader>
        
        <div className="space-y-6 py-4">
          {/* Report Meta Information */}
          <div className="grid grid-cols-2 gap-4 pb-4 border-b border-slate-200">
            <div>
              <p className="text-xs font-semibold text-slate-500 uppercase mb-1">Client</p>
              <p className="text-sm text-slate-900">{serviceUser?.full_name || 'Unknown'}</p>
            </div>
            <div>
              <p className="text-xs font-semibold text-slate-500 uppercase mb-1">Report Date</p>
              <p className="text-sm text-slate-900">{reportDate}</p>
            </div>
            <div>
              <p className="text-xs font-semibold text-slate-500 uppercase mb-1">Generated By</p>
              <p className="text-sm text-slate-900">{report.recorded_by_name}</p>
            </div>
            <div>
              <p className="text-xs font-semibold text-slate-500 uppercase mb-1">Generated Date</p>
              <p className="text-sm text-slate-900">{generatedDate}</p>
            </div>
          </div>

          {/* Report Content */}
          <div className="space-y-3">
            <p className="text-xs font-semibold text-slate-500 uppercase">Report Summary</p>
            <div className="bg-slate-50 p-4 rounded-lg border border-slate-200">
              <p className="text-sm text-slate-700 whitespace-pre-wrap leading-relaxed">
                {report.notes}
              </p>
            </div>
          </div>

          {/* Action Buttons */}
          <div className="flex gap-2 justify-end pt-4 border-t border-slate-200">
            <Button variant="outline" onClick={onClose}>
              Close
            </Button>
            <Button 
              onClick={handleDownload} 
              disabled={isDownloading}
              className="bg-teal-600 hover:bg-teal-700"
            >
              {isDownloading ? (
                <>
                  <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                  Downloading...
                </>
              ) : (
                <>
                  <Download className="w-4 h-4 mr-2" />
                  Download PDF
                </>
              )}
            </Button>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}