/**
 * Compliance Regulations Config
 *
 * Static definitions for CIW (Wales) and CQC (England) regulations.
 * Each regulation defines its form fields so the UI can render filing forms dynamically.
 * Adding a new regulation = adding an object here — no DB migration needed.
 */

// ── CIW Regulations (Wales) ─────────────────────────────────────────────────

const CIW_REGULATIONS = [
  {
    code: 'ciw_reg_73',
    framework: 'ciw',
    number: '73',
    title: 'Responsible Individual Visits',
    shortTitle: 'RI Visits',
    description:
      'The responsible individual must visit the service at least every 3 months to check on the wellbeing of service users and the running of the service.',
    legalRef: 'Regulated Services (Service Providers and Responsible Individuals) (Wales) Regulations 2017, Reg 73',
    cycle: { months: 3 },
    category: 'governance',
    guidance: {
      what: 'Under RISCA Regulation 73, the Responsible Individual (RI) must visit the service at least once every 3 months. The purpose is to assess the quality of care, speak with staff and service users, and identify any issues.',
      when: 'At least every 3 months (quarterly). The visit must be documented and a written report produced.',
      howToComplete: [
        'Record the date of your visit and whether it was in-person, virtual, or office-based.',
        'List all locations or service user homes you visited during this RI visit.',
        'Name the staff members you spoke with — include their roles (e.g. carer, senior, coordinator).',
        'Note which service users or relatives you consulted — what did they say about their care?',
        'Write your key observations about care quality, staff conduct, the environment, and service delivery.',
        'Summarise any feedback received from staff, service users, or families.',
        'Document any issues or concerns you identified during the visit.',
        'Set out specific actions required with who is responsible and by when.',
        'Give an overall assessment — this should honestly reflect what you found.',
      ],
      tips: 'Speak to service users privately where possible. Check care logs, MAR charts, and incident records during the visit. Compare findings with the previous RI visit report.',
    },
    fields: [
      { key: 'visit_date', label: 'Visit Date', type: 'date', required: true },
      { key: 'visit_type', label: 'Visit Type', type: 'select', options: ['In-person visit', 'Virtual visit', 'Office-based review', 'Service user home visit'], required: true },
      { key: 'locations_visited', label: 'Locations / Service Users Visited', type: 'textarea', placeholder: 'List locations or service user homes visited' },
      { key: 'staff_consulted', label: 'Staff Members Consulted', type: 'textarea', required: true, placeholder: 'Names and roles of staff spoken with' },
      { key: 'service_users_consulted', label: 'Service Users / Relatives Consulted', type: 'textarea', placeholder: 'Names of individuals or families spoken with' },
      { key: 'observations', label: 'Key Observations', type: 'textarea', required: true, placeholder: 'What was observed about care quality, staff conduct, environment...' },
      { key: 'feedback_received', label: 'Feedback Received', type: 'textarea', placeholder: 'Summary of feedback from staff, service users and relatives' },
      { key: 'issues_identified', label: 'Issues Identified', type: 'textarea', placeholder: 'Any concerns or issues noted during the visit' },
      { key: 'actions_required', label: 'Actions Required', type: 'textarea', placeholder: 'Specific actions with ownership and deadlines' },
      { key: 'overall_assessment', label: 'Overall Assessment', type: 'select', options: ['Satisfactory', 'Minor improvements needed', 'Significant improvements needed', 'Urgent action required'], required: true },
    ],
  },
  {
    code: 'ciw_reg_80',
    framework: 'ciw',
    number: '80',
    title: 'Quality of Care Review',
    shortTitle: 'Quality Review',
    description:
      'The responsible individual must establish a system for monitoring, reviewing and improving quality of care. A written report must be prepared at least every 6 months.',
    legalRef: 'Regulated Services (Service Providers and Responsible Individuals) (Wales) Regulations 2017, Reg 80',
    cycle: { months: 6 },
    category: 'quality',
    guidance: {
      what: 'Under RISCA Regulation 80, the RI must prepare a written report every 6 months reviewing the quality of care provided. This report must cover incidents, complaints, feedback, audits, and set out an action plan for improvement.',
      when: 'Every 6 months. The report covers a defined review period and must be retained for inspection.',
      howToComplete: [
        'Set the review period start and end dates (should be a 6-month window).',
        'Summarise all incidents during the period — total number, types, severity, and any trends.',
        'Record safeguarding referrals made — how many, what type, and what the outcomes were.',
        'Detail complaints received and how they were resolved. Note any lessons learned.',
        'Include any whistleblowing concerns raised and actions taken.',
        'Summarise staff engagement — supervision completion rates, training uptake, staff feedback.',
        'Include service user and family feedback from surveys, reviews, or direct conversations.',
        'Report on audit findings — care log audits, medication audits, record accuracy checks.',
        'Check care plan compliance — are plans up to date? Were review dates met?',
        'Write specific improvement recommendations based on your findings.',
        'Create an action plan with clear actions, responsible persons, deadlines, and review dates.',
        'Give an honest overall quality rating for the period.',
      ],
      tips: 'Use data from your incident log, complaints register, and supervision tracker to populate this report. Compare with the previous 6-month report to identify trends. This report is a key document inspectors will review.',
    },
    fields: [
      { key: 'review_period_start', label: 'Review Period Start', type: 'date', required: true },
      { key: 'review_period_end', label: 'Review Period End', type: 'date', required: true },
      { key: 'incidents_summary', label: 'Incidents Summary', type: 'textarea', required: true, placeholder: 'Total incidents, types, severity breakdown, trends...' },
      { key: 'safeguarding_referrals', label: 'Safeguarding Referrals', type: 'textarea', placeholder: 'Number of referrals, outcomes, any patterns' },
      { key: 'complaints_summary', label: 'Complaints Received & Resolution', type: 'textarea', placeholder: 'Number of complaints, nature, how resolved, lessons learned' },
      { key: 'whistleblowing', label: 'Whistleblowing Concerns', type: 'textarea', placeholder: 'Any whistleblowing concerns raised and actions taken' },
      { key: 'staff_feedback', label: 'Staff Engagement & Feedback', type: 'textarea', placeholder: 'Summary of staff feedback, supervision records, training uptake' },
      { key: 'service_user_feedback', label: 'Service User & Family Feedback', type: 'textarea', placeholder: 'Surveys, reviews, direct feedback summary' },
      { key: 'audit_findings', label: 'Audit Findings', type: 'textarea', required: true, placeholder: 'Results of care log audits, medication audits, record accuracy checks' },
      { key: 'care_plan_compliance', label: 'Care Plan Compliance', type: 'textarea', placeholder: 'Are care plans up to date? Review dates met?' },
      { key: 'improvement_recommendations', label: 'Improvement Recommendations', type: 'textarea', required: true, placeholder: 'Specific recommendations for improving the service' },
      { key: 'action_plan', label: 'Action Plan', type: 'textarea', required: true, placeholder: 'Actions, responsible person, deadlines, review dates' },
      { key: 'overall_quality_rating', label: 'Overall Quality Assessment', type: 'select', options: ['Excellent', 'Good', 'Adequate', 'Needs improvement', 'Inadequate'], required: true },
    ],
  },
  {
    code: 'ciw_reg_68',
    framework: 'ciw',
    number: '68',
    title: 'Fit & Proper Person (Manager)',
    shortTitle: 'Fit Person',
    description:
      'The service provider must ensure the manager is a fit and proper person. This includes checks on qualifications, DBS, registration and conduct.',
    legalRef: 'Regulated Services (Service Providers and Responsible Individuals) (Wales) Regulations 2017, Reg 68',
    cycle: { months: 12 },
    category: 'staffing',
    guidance: {
      what: 'Under RISCA Regulation 68, the service provider must ensure the registered manager is a "fit and proper person" — meaning they have the right qualifications, character, health, and DBS clearance to manage the service.',
      when: 'On appointment of a new manager, and reviewed annually thereafter.',
      howToComplete: [
        'Enter the manager\'s full name and their role/title.',
        'List all relevant qualifications (e.g. QCF/NVQ Level 5 in Leadership for Health & Social Care).',
        'Enter the DBS certificate date and whether they\'re on the DBS Update Service.',
        'Record their Social Care Wales registration number and expiry date.',
        'Confirm whether references have been verified (minimum 2 required).',
        'Confirm whether a health declaration has been received stating fitness to work.',
        'Add any additional notes about the fitness assessment.',
      ],
      tips: 'Keep copies of all certificates and declarations in the manager\'s HR file. Set a reminder for SCW registration renewal. CIW inspectors will ask to see this evidence.',
    },
    fields: [
      { key: 'manager_name', label: 'Manager Name', type: 'text', required: true },
      { key: 'manager_role', label: 'Role / Title', type: 'text', required: true },
      { key: 'qualifications', label: 'Qualifications Held', type: 'textarea', required: true, placeholder: 'List relevant qualifications (QCF/NVQ Level 5, etc.)' },
      { key: 'dbs_date', label: 'DBS Certificate Date', type: 'date', required: true },
      { key: 'dbs_update_service', label: 'Registered with DBS Update Service?', type: 'select', options: ['Yes', 'No'], required: true },
      { key: 'scw_registration', label: 'Social Care Wales Registration Number', type: 'text', placeholder: 'SCW registration number' },
      { key: 'scw_expiry', label: 'SCW Registration Expiry', type: 'date' },
      { key: 'references_verified', label: 'References Verified?', type: 'select', options: ['Yes', 'No', 'In progress'], required: true },
      { key: 'health_declaration', label: 'Health Declaration Received?', type: 'select', options: ['Yes', 'No'], required: true },
      { key: 'declaration_notes', label: 'Additional Notes', type: 'textarea', placeholder: 'Any notes on fitness assessment, conditions, etc.' },
    ],
  },
  {
    code: 'ciw_reg_72',
    framework: 'ciw',
    number: '72',
    title: 'Manager Absence Cover',
    shortTitle: 'Absence Cover',
    description:
      'If the manager is absent for 28 days or more, the responsible individual must make suitable cover arrangements and notify CIW.',
    legalRef: 'Regulated Services (Service Providers and Responsible Individuals) (Wales) Regulations 2017, Reg 72',
    cycle: null, // event-driven
    category: 'governance',
    guidance: {
      what: 'Under RISCA Regulation 72, if the registered manager is absent for 28 continuous days or more, the RI must put suitable cover in place and notify CIW. This ensures the service is never left without competent leadership.',
      when: 'As soon as you know the manager will be absent for 28+ days. CIW must be notified promptly — do not wait until day 28.',
      howToComplete: [
        'Enter the absent manager\'s name and the reason for absence.',
        'Record the absence start date and expected return date (if known).',
        'Name the cover manager and describe their relevant qualifications and experience.',
        'Enter the date CIW was notified of the absence.',
        'Describe the cover arrangements — how will service continuity be maintained?',
      ],
      tips: 'The cover manager should ideally hold similar qualifications. Notify CIW early rather than late. Keep a copy of the notification confirmation from CIW.',
    },
    fields: [
      { key: 'manager_name', label: 'Absent Manager Name', type: 'text', required: true },
      { key: 'absence_reason', label: 'Reason for Absence', type: 'select', options: ['Sickness', 'Annual leave', 'Maternity/Paternity', 'Suspension', 'Resignation', 'Other'], required: true },
      { key: 'absence_start', label: 'Absence Start Date', type: 'date', required: true },
      { key: 'expected_return', label: 'Expected Return Date', type: 'date' },
      { key: 'cover_name', label: 'Cover Manager Name', type: 'text', required: true },
      { key: 'cover_qualifications', label: 'Cover Manager Qualifications', type: 'textarea', placeholder: 'Relevant qualifications and experience' },
      { key: 'ciw_notified_date', label: 'Date CIW Notified', type: 'date', required: true },
      { key: 'cover_arrangements', label: 'Cover Arrangements Details', type: 'textarea', required: true, placeholder: 'How service continuity will be maintained' },
    ],
  },
  {
    code: 'ciw_reg_60',
    framework: 'ciw',
    number: '60',
    title: 'Notifications to CIW',
    shortTitle: 'CIW Notification',
    description:
      'The service provider must notify CIW of specific events including safeguarding incidents, serious injuries, deaths, allegations against staff, and enforcement actions.',
    legalRef: 'Regulated Services (Service Providers and Responsible Individuals) (Wales) Regulations 2017, Reg 60',
    cycle: null, // event-driven
    category: 'notifications',
    guidance: {
      what: 'Under RISCA Regulation 60, certain events must be reported to CIW without delay. These include: deaths, serious injuries, safeguarding incidents, allegations against staff, whistleblowing concerns, and enforcement actions.',
      when: 'As soon as practicable after the event. Most notifications should be made within 24 hours. Use CIW Online for formal submissions.',
      howToComplete: [
        'Select the event type from the dropdown — this determines what CIW expects to see.',
        'Enter the exact date and time the event occurred.',
        'List all people involved — names and roles (service users, staff, visitors, etc.).',
        'Write a detailed factual description of what happened. Stick to facts, not opinions.',
        'Describe immediate actions taken to protect people and manage the situation.',
        'Record which external agencies were notified (police, local authority, GP, etc.) and when.',
        'Select how you notified CIW and the date of notification.',
        'Outline follow-up actions — ongoing investigation, support measures, planned reviews.',
      ],
      tips: 'Use CIW Online (online.ciw.wales) for notifications where possible. Keep a copy of every notification for your records. If in doubt whether something is notifiable, notify anyway — it\'s better to over-report than under-report.',
    },
    fields: [
      { key: 'event_type', label: 'Event Type', type: 'select', options: ['Safeguarding incident', 'Serious injury', 'Death of service user', 'Allegation against staff', 'Whistleblowing concern', 'Enforcement action', 'Significant complaint', 'Other notifiable event'], required: true },
      { key: 'event_date', label: 'Event Date', type: 'date', required: true },
      { key: 'event_time', label: 'Event Time', type: 'time' },
      { key: 'people_involved', label: 'People Involved', type: 'textarea', required: true, placeholder: 'Names and roles of all people involved' },
      { key: 'description', label: 'Description of Event', type: 'textarea', required: true, placeholder: 'Detailed description of what happened' },
      { key: 'immediate_actions', label: 'Immediate Actions Taken', type: 'textarea', required: true, placeholder: 'What was done immediately in response' },
      { key: 'agencies_notified', label: 'External Agencies Notified', type: 'textarea', placeholder: 'Police, local authority, CSSIW, etc. with dates' },
      { key: 'ciw_notification_method', label: 'CIW Notification Method', type: 'select', options: ['CIW Online', 'Email', 'Phone', 'Letter'], required: true },
      { key: 'ciw_notification_date', label: 'Date Notified to CIW', type: 'date', required: true },
      { key: 'follow_up', label: 'Follow-up Actions', type: 'textarea', placeholder: 'Ongoing investigation, support measures, reviews planned' },
    ],
  },
];

// ── CQC Regulations (England) ───────────────────────────────────────────────

const CQC_REGULATIONS = [
  {
    code: 'cqc_reg_17',
    framework: 'cqc',
    number: '17',
    title: 'Good Governance',
    shortTitle: 'Governance',
    description:
      'Systems and processes must be established to assess, monitor and improve the quality and safety of the services provided, including risk assessment and audit.',
    legalRef: 'Health and Social Care Act 2008 (Regulated Activities) Regulations 2014, Reg 17',
    cycle: { months: 6 },
    category: 'quality',
    guidance: {
      what: 'CQC Regulation 17 requires providers to have effective governance systems. You must be able to demonstrate how you assess, monitor, and improve the quality and safety of your services.',
      when: 'Review and report every 6 months. This is a core part of CQC\'s "Well-led" key question.',
      howToComplete: [
        'Set the 6-month review period dates.',
        'Describe your current governance structure — who is responsible for what.',
        'Summarise key risks identified and what you\'re doing to mitigate them.',
        'Analyse all incidents and accidents — totals, trends, and lessons learned.',
        'Review complaints — themes, how they were resolved, what changed as a result.',
        'Report on audit results — care audits, medication audits, record audits.',
        'Include staff feedback from supervisions, surveys, or team meetings.',
        'Include service user and carer feedback — surveys, reviews, direct conversations.',
        'Write a quality improvement plan with specific actions, owners, and timelines.',
        'Give an honest self-assessment rating.',
      ],
      tips: 'CQC inspectors look for evidence that you learn from mistakes and continuously improve. Link your findings to specific actions. Show that previous actions were followed up.',
    },
    fields: [
      { key: 'review_period_start', label: 'Review Period Start', type: 'date', required: true },
      { key: 'review_period_end', label: 'Review Period End', type: 'date', required: true },
      { key: 'governance_structure', label: 'Governance Structure Review', type: 'textarea', placeholder: 'Current governance arrangements, any changes' },
      { key: 'risk_assessment', label: 'Risk Assessment Summary', type: 'textarea', required: true, placeholder: 'Key risks identified, mitigation measures' },
      { key: 'incidents_analysis', label: 'Incidents & Accidents Analysis', type: 'textarea', required: true, placeholder: 'Total incidents, trends, lessons learned' },
      { key: 'complaints_analysis', label: 'Complaints Analysis', type: 'textarea', placeholder: 'Complaints received, themes, resolution, learning' },
      { key: 'audit_results', label: 'Audit Results', type: 'textarea', required: true, placeholder: 'Results of care audits, medication audits, record audits' },
      { key: 'staff_feedback', label: 'Staff Feedback & Engagement', type: 'textarea', placeholder: 'Staff survey results, supervision feedback, training' },
      { key: 'service_user_feedback', label: 'Service User & Carer Feedback', type: 'textarea', placeholder: 'Feedback mechanisms, survey results, actions taken' },
      { key: 'quality_improvement_plan', label: 'Quality Improvement Plan', type: 'textarea', required: true, placeholder: 'Specific improvements, responsible persons, timelines' },
      { key: 'overall_rating', label: 'Self-Assessment Rating', type: 'select', options: ['Outstanding', 'Good', 'Requires improvement', 'Inadequate'], required: true },
    ],
  },
  {
    code: 'cqc_reg_13',
    framework: 'cqc',
    number: '13',
    title: 'Safeguarding',
    shortTitle: 'Safeguarding',
    description:
      'Service users must be protected from abuse and improper treatment. Systems and processes must be established to prevent abuse and investigate concerns.',
    legalRef: 'Health and Social Care Act 2008 (Regulated Activities) Regulations 2014, Reg 13',
    cycle: { months: 6 },
    category: 'safeguarding',
    guidance: {
      what: 'CQC Regulation 13 requires providers to have robust safeguarding systems. You must protect people from abuse and improper treatment, investigate concerns, and work with local authorities.',
      when: 'Review every 6 months. Safeguarding referrals should be made immediately when concerns arise.',
      howToComplete: [
        'Set the review period dates.',
        'Detail all safeguarding referrals made — how many, what types, and outcomes.',
        'Report on staff safeguarding training compliance — percentage trained, gaps, refresher dates.',
        'Confirm when the safeguarding policy was last reviewed and any updates made.',
        'Cover MCA (Mental Capacity Act) assessments, DoLS applications, and best interest decisions.',
        'Review any restraint or restrictive practices — justification and alternatives explored.',
        'Report any whistleblowing concerns and how they were handled.',
        'Set out actions and improvements to strengthen safeguarding.',
      ],
      tips: 'CQC expects a "zero tolerance" culture for abuse. Ensure all staff know how to recognise and report abuse. Keep a safeguarding log with clear audit trails. Train new staff in safeguarding within their first week.',
    },
    fields: [
      { key: 'review_period_start', label: 'Review Period Start', type: 'date', required: true },
      { key: 'review_period_end', label: 'Review Period End', type: 'date', required: true },
      { key: 'safeguarding_referrals', label: 'Safeguarding Referrals Made', type: 'textarea', required: true, placeholder: 'Number, types, outcomes of referrals' },
      { key: 'training_compliance', label: 'Staff Safeguarding Training Compliance', type: 'textarea', required: true, placeholder: 'Percentage trained, any gaps, refresher schedule' },
      { key: 'policies_review', label: 'Safeguarding Policy Review', type: 'textarea', placeholder: 'When last reviewed, any updates, next review date' },
      { key: 'mental_capacity', label: 'Mental Capacity & DoLS', type: 'textarea', placeholder: 'MCA assessments, DoLS applications, best interest decisions' },
      { key: 'restraint_review', label: 'Restraint / Restrictive Practice Review', type: 'textarea', placeholder: 'Any restrictive practices, justification, alternatives explored' },
      { key: 'whistleblowing', label: 'Whistleblowing', type: 'textarea', placeholder: 'Any concerns raised, how handled, outcomes' },
      { key: 'actions', label: 'Actions & Improvements', type: 'textarea', required: true, placeholder: 'Steps to strengthen safeguarding' },
    ],
  },
  {
    code: 'cqc_reg_19',
    framework: 'cqc',
    number: '19',
    title: 'Fit & Proper Persons Employed',
    shortTitle: 'Fit Persons',
    description:
      'Persons employed must be of good character, have the qualifications and skills necessary, and be physically and mentally fit for the work.',
    legalRef: 'Health and Social Care Act 2008 (Regulated Activities) Regulations 2014, Reg 19',
    cycle: { months: 12 },
    category: 'staffing',
    guidance: {
      what: 'CQC Regulation 19 requires that all persons employed are "fit and proper" — they must have the right character, qualifications, skills, experience, and health to do their job safely.',
      when: 'Completed for each new employee at recruitment, and reviewed annually.',
      howToComplete: [
        'Enter the staff member\'s name and their role/position.',
        'Record the DBS certificate date and level (Enhanced with barred list check for care roles).',
        'List relevant qualifications — Care Certificate, NVQ/QCF, first aid, etc.',
        'Confirm references obtained — CQC expects at least 2 satisfactory references.',
        'Confirm right to work has been verified with original documents.',
        'Record health declaration status — any adjustments needed?',
        'Note any previous conduct or disciplinary checks with former employers.',
        'Add any additional notes relevant to the fitness assessment.',
      ],
      tips: 'Safe recruitment is a CQC "must do". Never allow someone to start work without a DBS check. Keep a recruitment checklist for every new starter. CQC inspectors will sample staff files to check compliance.',
    },
    fields: [
      { key: 'staff_member_name', label: 'Staff Member Name', type: 'text', required: true },
      { key: 'role', label: 'Role / Position', type: 'text', required: true },
      { key: 'dbs_date', label: 'DBS Certificate Date', type: 'date', required: true },
      { key: 'dbs_level', label: 'DBS Level', type: 'select', options: ['Enhanced', 'Enhanced with barred list', 'Standard'], required: true },
      { key: 'qualifications', label: 'Qualifications', type: 'textarea', required: true, placeholder: 'Relevant qualifications (Care Certificate, NVQ, etc.)' },
      { key: 'references', label: 'References Obtained', type: 'select', options: ['Yes - 2 references', 'Yes - 1 reference', 'Pending', 'Not yet obtained'], required: true },
      { key: 'right_to_work', label: 'Right to Work Verified', type: 'select', options: ['Yes', 'No', 'Pending'], required: true },
      { key: 'health_declaration', label: 'Health Declaration', type: 'select', options: ['Received - fit', 'Received - adjustments needed', 'Not yet received'], required: true },
      { key: 'conduct_check', label: 'Previous Conduct / Disciplinary Check', type: 'textarea', placeholder: 'Any previous employers contacted re conduct' },
      { key: 'notes', label: 'Additional Notes', type: 'textarea' },
    ],
  },
  {
    code: 'cqc_reg_20',
    framework: 'cqc',
    number: '20',
    title: 'Duty of Candour',
    shortTitle: 'Duty of Candour',
    description:
      'When a notifiable safety incident occurs, the provider must act in an open and transparent way, notify the relevant person, and provide a written account.',
    legalRef: 'Health and Social Care Act 2008 (Regulated Activities) Regulations 2014, Reg 20',
    cycle: null, // event-driven
    category: 'notifications',
    guidance: {
      what: 'CQC Regulation 20 (Duty of Candour) requires that when a "notifiable safety incident" occurs — one that results in moderate harm, severe harm, or death — the provider must be open and honest with the person affected (or their family).',
      when: 'As soon as reasonably practicable after the incident. Verbal notification should happen within 10 working days. Written notification must follow.',
      howToComplete: [
        'Record the incident date and write a factual description of what happened.',
        'Name the person affected and the level of harm (moderate, severe, or death).',
        'Record when you gave verbal notification and to whom (name and relationship).',
        'Record when written notification was sent.',
        'Confirm that a sincere apology was given — this is a legal requirement, not optional.',
        'Summarise the investigation findings — root cause, contributing factors.',
        'Describe actions taken to prevent recurrence — system changes, training, process improvements.',
        'Record whether CQC was notified and the date.',
      ],
      tips: 'An apology is NOT an admission of liability — it is a legal requirement under Duty of Candour. Be honest and compassionate. Keep copies of all written notifications. The family has a right to request the investigation report.',
    },
    fields: [
      { key: 'incident_date', label: 'Incident Date', type: 'date', required: true },
      { key: 'incident_description', label: 'Description of Notifiable Safety Incident', type: 'textarea', required: true, placeholder: 'What happened, who was affected, what harm occurred' },
      { key: 'person_affected', label: 'Person Affected', type: 'text', required: true },
      { key: 'harm_level', label: 'Level of Harm', type: 'select', options: ['Moderate harm', 'Severe harm', 'Death'], required: true },
      { key: 'verbal_notification_date', label: 'Date of Verbal Notification', type: 'date', required: true },
      { key: 'verbal_notification_to', label: 'Verbal Notification Given To', type: 'text', required: true, placeholder: 'Name and relationship of person notified' },
      { key: 'written_notification_date', label: 'Date of Written Notification', type: 'date', required: true },
      { key: 'apology_given', label: 'Apology Given?', type: 'select', options: ['Yes', 'No'], required: true },
      { key: 'investigation_summary', label: 'Investigation Summary', type: 'textarea', required: true, placeholder: 'Findings, root cause, contributing factors' },
      { key: 'actions_taken', label: 'Actions Taken to Prevent Recurrence', type: 'textarea', required: true, placeholder: 'Steps taken, system changes, training' },
      { key: 'cqc_notified', label: 'CQC Notified?', type: 'select', options: ['Yes', 'No', 'Not applicable'], required: true },
      { key: 'cqc_notification_date', label: 'CQC Notification Date', type: 'date' },
    ],
  },
  {
    code: 'cqc_reg_16',
    framework: 'cqc',
    number: '16',
    title: 'Complaints Handling',
    shortTitle: 'Complaints',
    description:
      'An accessible system must be established for identifying, receiving, recording, handling and responding to complaints.',
    legalRef: 'Health and Social Care Act 2008 (Regulated Activities) Regulations 2014, Reg 16',
    cycle: { months: 6 },
    category: 'quality',
    guidance: {
      what: 'CQC Regulation 16 requires an accessible, effective complaints system. People must feel safe to complain without fear of reprisal. All complaints must be investigated, responded to, and used for learning.',
      when: 'Review complaints handling every 6 months. Individual complaints must be acknowledged within 3 working days and resolved within a reasonable timeframe.',
      howToComplete: [
        'Set the review period dates.',
        'Record the total number of complaints received during the period.',
        'Identify common themes — what do people complain about most?',
        'Summarise how complaints were resolved and the average resolution time.',
        'Note how many complaints were upheld or partially upheld.',
        'Record any complaints escalated to the ombudsman or external bodies.',
        'Document lessons learned — what changes were made as a result of complaints?',
        'Confirm when the complaints policy was last reviewed and any updates made.',
      ],
      tips: 'Treat every complaint as an opportunity to improve. CQC inspectors will check that you respond to complaints promptly and that you can demonstrate learning. Make the complaints process visible — display it in welcome packs and on notice boards.',
    },
    fields: [
      { key: 'review_period_start', label: 'Review Period Start', type: 'date', required: true },
      { key: 'review_period_end', label: 'Review Period End', type: 'date', required: true },
      { key: 'total_complaints', label: 'Total Complaints Received', type: 'text', required: true },
      { key: 'complaint_themes', label: 'Common Themes', type: 'textarea', required: true, placeholder: 'Most frequent complaint categories, patterns' },
      { key: 'resolution_summary', label: 'Resolution Summary', type: 'textarea', required: true, placeholder: 'How complaints were resolved, average resolution time' },
      { key: 'upheld_complaints', label: 'Complaints Upheld / Partially Upheld', type: 'text', placeholder: 'Number upheld' },
      { key: 'escalated', label: 'Complaints Escalated', type: 'textarea', placeholder: 'Any escalated to ombudsman or external body' },
      { key: 'lessons_learned', label: 'Lessons Learned', type: 'textarea', required: true, placeholder: 'Changes made as a result of complaints' },
      { key: 'policy_review', label: 'Complaints Policy Review', type: 'textarea', placeholder: 'Last reviewed, any changes, accessibility' },
    ],
  },
  {
    code: 'cqc_reg_18',
    framework: 'cqc',
    number: '18',
    title: 'Staffing',
    shortTitle: 'Staffing',
    description:
      'Sufficient numbers of suitably qualified, competent, skilled and experienced staff must be deployed to meet care needs at all times.',
    legalRef: 'Health and Social Care Act 2008 (Regulated Activities) Regulations 2014, Reg 18',
    cycle: { months: 6 },
    category: 'staffing',
    guidance: {
      what: 'CQC Regulation 18 requires sufficient numbers of suitably qualified, competent, skilled and experienced staff at all times. Staff must receive appropriate support, training, supervision, and appraisal.',
      when: 'Review every 6 months. Staffing levels should be continuously monitored.',
      howToComplete: [
        'Set the review period dates.',
        'Record your total staff count.',
        'Note current vacancies and any impact on service delivery.',
        'Calculate and record staff turnover rate for the period.',
        'Record sickness absence rate.',
        'Report on mandatory training compliance — percentage complete for each course.',
        'Report on supervision compliance — are all staff receiving regular supervision?',
        'Describe recruitment activity — roles recruited, safe recruitment process compliance.',
        'Note any staffing concerns, risks, or gaps.',
        'Set out actions and improvements for the next period.',
      ],
      tips: 'CQC expects you to demonstrate that staffing levels are safe. Use dependency tools to calculate required hours. Track training expiry dates proactively. Ensure all staff have at least quarterly supervision (12-weekly recommended).',
    },
    fields: [
      { key: 'review_period_start', label: 'Review Period Start', type: 'date', required: true },
      { key: 'review_period_end', label: 'Review Period End', type: 'date', required: true },
      { key: 'total_staff', label: 'Total Staff Count', type: 'text', required: true },
      { key: 'vacancies', label: 'Current Vacancies', type: 'text' },
      { key: 'turnover_rate', label: 'Staff Turnover Rate', type: 'text', placeholder: 'e.g. 15%' },
      { key: 'sickness_absence', label: 'Sickness Absence Rate', type: 'text', placeholder: 'e.g. 3.5%' },
      { key: 'training_compliance', label: 'Mandatory Training Compliance', type: 'textarea', required: true, placeholder: 'Percentage completion for each mandatory course' },
      { key: 'supervision_compliance', label: 'Supervision Compliance', type: 'textarea', placeholder: 'Staff receiving regular supervision, frequency' },
      { key: 'recruitment_activity', label: 'Recruitment Activity', type: 'textarea', placeholder: 'Roles recruited, safe recruitment process compliance' },
      { key: 'staffing_concerns', label: 'Staffing Concerns', type: 'textarea', placeholder: 'Any gaps, risks, planned mitigations' },
      { key: 'actions', label: 'Actions & Improvements', type: 'textarea', required: true },
    ],
  },
];

// ── Exports ─────────────────────────────────────────────────────────────────

export const REGULATIONS = [...CIW_REGULATIONS, ...CQC_REGULATIONS];

export const REGULATION_MAP = Object.fromEntries(REGULATIONS.map((r) => [r.code, r]));

export const getRegulationsByFramework = (framework) =>
  REGULATIONS.filter((r) => r.framework === framework);

export const CATEGORY_LABELS = {
  governance: 'Governance',
  quality: 'Quality Assurance',
  safeguarding: 'Safeguarding',
  staffing: 'Staffing',
  notifications: 'Notifications',
};

export const FRAMEWORK_LABELS = {
  ciw: 'CIW (Care Inspectorate Wales)',
  cqc: 'CQC (Care Quality Commission)',
};
