/**
 * careLogPDF.js
 * Client-side care log batch PDF generator using jsPDF.
 * Produces a professional cover sheet + one section per log entry.
 * Used in ServiceUserDetails → Care Logs tab.
 */
import { jsPDF } from 'jspdf';
import { supabase } from '@/api/supabaseClient';

const BRAND_BLUE = [30, 58, 138];
const SLATE_100 = [241, 245, 249];
const BLUE_100 = [219, 234, 254];
const GREEN_50 = [240, 253, 244];
const SLATE_400 = [148, 163, 184];

function getBodyRegion(x, y) {
  if (y < 0.15) return 'Head';
  if (y < 0.25) return x < 0.35 ? 'Right Shoulder' : x > 0.65 ? 'Left Shoulder' : 'Neck/Upper Chest';
  if (y < 0.35) return x < 0.25 ? 'Right Arm' : x > 0.75 ? 'Left Arm' : 'Upper Torso';
  if (y < 0.50) return x < 0.25 ? 'Right Arm' : x > 0.75 ? 'Left Arm' : 'Lower Torso';
  if (y < 0.55) return 'Hip Area';
  if (y < 0.75) return x < 0.40 ? 'Right Thigh' : x > 0.60 ? 'Left Thigh' : 'Upper Legs';
  if (y < 0.90) return x < 0.40 ? 'Right Lower Leg' : x > 0.60 ? 'Left Lower Leg' : 'Lower Legs';
  return x < 0.40 ? 'Right Foot' : x > 0.60 ? 'Left Foot' : 'Feet';
}

/**
 * Fetch care logs for a client within a date range, then generate and download a PDF.
 * @param {object} serviceUser  - { id, full_name, date_of_birth, address, care_type }
 * @param {string} startDate    - YYYY-MM-DD
 * @param {string} endDate      - YYYY-MM-DD
 * @param {object} currentUser  - { full_name, role, organization_id }
 * @param {object} orgName      - organisation name string
 */
export async function downloadCareLogsPDF(serviceUser, startDate, endDate, currentUser, orgName) {
  // ── 1. Fetch logs from Supabase ─────────────────────────────────────────
  const { data: logs, error } = await supabase
    .from('care_logs')
    .select('*')
    .eq('service_user_id', serviceUser.id)
    .gte('visit_date', startDate)
    .lte('visit_date', endDate)
    .order('visit_date', { ascending: true })
    .order('visit_time', { ascending: true });

  if (error) throw new Error('Failed to fetch care logs: ' + error.message);

  // Fetch custom field labels if available
  let formConfigs = [];
  try {
    const { data } = await supabase.from('care_log_form_configs').select('*');
    formConfigs = data || [];
  } catch (_e) { /* ignore */ }

  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  doc.setFont('helvetica');
  const pageWidth = doc.internal.pageSize.width;
  const pageHeight = doc.internal.pageSize.height;
  const margin = 20;
  const clientName = serviceUser.full_name || 'Client';
  const totalLogs = logs?.length || 0;

  // ── 2. Cover Sheet ──────────────────────────────────────────────────────
  doc.setFillColor(...BRAND_BLUE);
  doc.rect(0, 0, pageWidth, 42, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text('Care Log Report', margin, 23);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.text(orgName || 'Care Provider', margin, 35);

  doc.setTextColor(0, 0, 0);

  // Client details box
  doc.setFillColor(...SLATE_100);
  doc.roundedRect(margin, 52, pageWidth - margin * 2, 58, 3, 3, 'F');
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('Client Details', margin + 6, 64);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');

  doc.setFont('helvetica', 'bold');
  doc.text('Name:', margin + 6, 74);
  doc.setFont('helvetica', 'normal');
  doc.text(clientName, margin + 26, 74);

  if (serviceUser.date_of_birth) {
    doc.setFont('helvetica', 'bold');
    doc.text('Date of Birth:', margin + 6, 82);
    doc.setFont('helvetica', 'normal');
    doc.text(serviceUser.date_of_birth, margin + 44, 82);
  }

  if (serviceUser.address) {
    doc.setFont('helvetica', 'bold');
    doc.text('Address:', margin + 6, 90);
    doc.setFont('helvetica', 'normal');
    const addr = doc.splitTextToSize(serviceUser.address, pageWidth - margin * 2 - 38);
    doc.text(addr[0], margin + 30, 90);
    if (addr[1]) doc.text(addr[1], margin + 30, 96);
  }

  if (serviceUser.care_type) {
    doc.setFont('helvetica', 'bold');
    doc.text('Care Type:', margin + 6, 102);
    doc.setFont('helvetica', 'normal');
    doc.text(serviceUser.care_type.replace(/_/g, ' '), margin + 34, 102);
  }

  // Report period box
  doc.setFillColor(...BLUE_100);
  doc.roundedRect(margin, 120, pageWidth - margin * 2, 38, 3, 3, 'F');
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('Report Period', margin + 6, 132);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`From: ${startDate}`, margin + 6, 142);
  doc.text(`To: ${endDate}`, margin + 70, 142);
  doc.text(`Total Entries: ${totalLogs}`, margin + 134, 142);
  doc.text(`Generated: ${new Date().toLocaleDateString('en-GB')}`, margin + 6, 150);
  if (currentUser?.full_name) {
    doc.text(`Generated by: ${currentUser.full_name}`, margin + 90, 150);
  }

  // Provider box
  if (orgName) {
    doc.setFillColor(...GREEN_50);
    doc.roundedRect(margin, 168, pageWidth - margin * 2, 28, 3, 3, 'F');
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('Care Provider', margin + 6, 180);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(orgName, margin + 6, 189);
  }

  // Confidentiality footer
  doc.setFontSize(8);
  doc.setTextColor(...SLATE_400);
  doc.text(
    'CONFIDENTIAL — This document contains personal care information. Handle in accordance with GDPR and organisational policy.',
    margin, pageHeight - 12,
    { maxWidth: pageWidth - margin * 2 }
  );
  doc.setTextColor(0, 0, 0);

  if (totalLogs === 0) {
    doc.addPage();
    doc.setFontSize(13);
    doc.setTextColor(...SLATE_400);
    doc.text('No care log entries found for the selected date range.', pageWidth / 2, pageHeight / 2, { align: 'center' });
    doc.setTextColor(0, 0, 0);
    doc.save(`${clientName.replace(/\s+/g, '-')}_care-logs_${startDate}_to_${endDate}.pdf`);
    return 0;
  }

  // ── 3. One page-group per log entry ──────────────────────────────────────
  logs.forEach((log, index) => {
    doc.addPage();
    let y = margin;

    // Entry header bar
    doc.setFillColor(...BRAND_BLUE);
    doc.rect(0, 0, pageWidth, 16, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    const headerText = `Entry ${index + 1} of ${totalLogs}  •  ${log.visit_date}${log.visit_time ? ' at ' + log.visit_time : ''}  •  ${clientName}`;
    doc.text(headerText, margin, 11);
    doc.setTextColor(0, 0, 0);
    y = 26;

    // Helper: add a labelled line
    const addLine = (label, value, indent = false) => {
      if (!value) return;
      if (y > pageHeight - 20) { doc.addPage(); y = margin; }
      const x = indent ? margin + 8 : margin;
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(9);
      const lw = doc.getTextWidth(label + '  ');
      doc.text(label, x, y);
      doc.setFont('helvetica', 'normal');
      const wrapped = doc.splitTextToSize(String(value), pageWidth - x - margin - lw);
      doc.text(wrapped[0], x + lw, y);
      for (let i = 1; i < wrapped.length; i++) {
        y += 5;
        if (y > pageHeight - 20) { doc.addPage(); y = margin; }
        doc.text(wrapped[i], x + lw, y);
      }
      y += 6;
    };

    // Helper: section heading strip
    const addSection = (title) => {
      if (y > pageHeight - 30) { doc.addPage(); y = margin; }
      y += 2;
      doc.setFillColor(...SLATE_100);
      doc.rect(margin, y - 4, pageWidth - margin * 2, 8, 'F');
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(9);
      doc.text(title, margin + 3, y + 1);
      doc.setFont('helvetica', 'normal');
      y += 9;
    };

    // Helper: block of wrapped text
    const addBlock = (label, text) => {
      if (!text) return;
      addSection(label);
      const wrapped = doc.splitTextToSize(text, pageWidth - margin * 2 - 8);
      wrapped.forEach(line => {
        if (y > pageHeight - 20) { doc.addPage(); y = margin; }
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(9);
        doc.text(line, margin + 8, y);
        y += 5;
      });
    };

    addSection('Visit Summary');
    addLine('Staff:', log.staff_name);
    addLine('Status:', log.status ? log.status.charAt(0).toUpperCase() + log.status.slice(1) : null);
    addLine('Duration:', log.duration_minutes ? `${log.duration_minutes} minutes` : null);
    addLine('Double Handed:', log.double_handed_call);
    addLine('Staff Grade:', log.staff_grade);

    addSection('Welfare & Observations');
    addLine('Welfare on Arrival:', log.welfare_impression_on_arrival?.replace(/_/g, ' '));
    addLine('Mood:', log.mood ? log.mood.charAt(0).toUpperCase() + log.mood.slice(1) : null);
    if (log.observations) addBlock('Observations', log.observations);

    addSection('Personal Care');
    addLine('Personal Care:', log.personal_care);
    addLine('Details:', log.personal_care_description, true);
    addLine('Continence Care:', log.continence_care_provided);
    addLine('Catheter Care:', log.catheter_care_provided);
    addLine('Catheter Details:', log.catheter_care_description, true);
    addLine('Repositioned:', log.repositioned_on_visit);
    addLine('Skincare:', log.skincare_provided);
    addLine('Skin Integrity Concerns:', log.skin_integrity_concerns);

    addSection('Nutrition & Fluids');
    addLine('Food Intake:', log.food_intake ? log.food_intake.charAt(0).toUpperCase() + log.food_intake.slice(1) : null);
    addLine('Food Offered:', log.food_offered);
    addLine('Accepted:', log.food_accepted, true);
    addLine('What Given:', log.food_given, true);
    addLine('Food Outcome:', log.food_outcome?.replace(/_/g, ' '), true);
    addLine('Fluid Intake:', log.fluid_intake ? log.fluid_intake.charAt(0).toUpperCase() + log.fluid_intake.slice(1) : null);
    addLine('Drinks Offered:', log.drinks_offered);
    addLine('Accepted:', log.drinks_accepted, true);
    addLine('What Given:', log.drinks_given, true);
    addLine('Drinks Outcome:', log.drinks_outcome?.replace(/_/g, ' '), true);

    addSection('Medications');
    addLine('Medication Round:', log.add_medication_round);
    addLine('Outcome:', log.medication_round_outcome, true);
    if (log.medication_concerns && log.medication_concerns !== 'no') {
      addLine('Medication Concerns:', log.medication_concerns);
      addLine('Details:', log.medication_concerns_details, true);
    }

    if (log.healthcare_visit_required && log.healthcare_visit_required !== 'no') {
      addSection('Healthcare Referral');
      addLine('Visit Required:', log.healthcare_visit_required);
      addLine('Type:', log.healthcare_visit_type, true);
    }

    if (log.further_concerns && log.further_concerns !== 'no') {
      addSection('Concerns & Incidents');
      addLine('Further Concerns:', log.further_concerns);
      addLine('Details:', log.further_concerns_details, true);
    }

    // Body map markers
    if (Array.isArray(log.body_map_markers) && log.body_map_markers.length > 0) {
      addSection('Body Map Markers');
      log.body_map_markers.forEach((marker, idx) => {
        const side = marker.side === 'front' ? 'Front' : 'Back';
        const region = getBodyRegion(marker.x, marker.y);
        const note = marker.note ? ` — ${marker.note}` : '';
        addLine(`${idx + 1}.`, `${side} body, ${region}${note}`);
      });
    }

    if (log.extended_notes) addBlock('Extended Notes', log.extended_notes);

    // Custom form builder fields
    if (log.custom_fields && typeof log.custom_fields === 'object') {
      for (const [sectionId, fields] of Object.entries(log.custom_fields)) {
        if (!fields || typeof fields !== 'object' || Object.keys(fields).length === 0) continue;

        let sectionLabel = sectionId.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase());
        for (const cfg of formConfigs) {
          const sections = cfg.config?.sections || [];
          const match = sections.find(s => s.id === sectionId && s.type === 'custom');
          if (match) { sectionLabel = match.label || match.name || sectionLabel; break; }
        }
        addSection(sectionLabel);

        for (const [fieldId, value] of Object.entries(fields)) {
          if (value === null || value === undefined || value === '') continue;
          let fieldLabel = fieldId.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase()) + ':';
          for (const cfg of formConfigs) {
            const section = (cfg.config?.sections || []).find(s => s.id === sectionId);
            if (section?.fields) {
              const fld = section.fields.find(f => f.id === fieldId);
              if (fld) { fieldLabel = (fld.label || fieldLabel) + ':'; break; }
            }
          }
          addLine(fieldLabel, Array.isArray(value) ? value.join(', ') : String(value));
        }
      }
    }

    // Page footer
    doc.setFontSize(7);
    doc.setTextColor(...SLATE_400);
    doc.text(
      `${clientName}  |  Care Log  |  ${log.visit_date}  |  Page ${index + 2}`,
      margin, pageHeight - 8
    );
    doc.setTextColor(0, 0, 0);
  });

  // ── 4. Save ──────────────────────────────────────────────────────────────
  const filename = `${clientName.replace(/\s+/g, '-')}_care-logs_${startDate}_to_${endDate}.pdf`;
  doc.save(filename);
  return totalLogs;
}
